// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WaterTransportService.Model.Context;

#nullable disable

namespace WaterTransportService.Model.Migrations
{
    [DbContext(typeof(WaterTransportDbContext))]
    [Migration("20251017071334_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.Property<long>("RolesId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("UsersUuid")
                        .HasColumnType("uuid");

                    b.HasKey("RolesId", "UsersUuid");

                    b.HasIndex("UsersUuid");

                    b.ToTable("RoleUser");
                });

            modelBuilder.Entity("WaterTransportService.Model.Entities.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("BookingStatusId")
                        .HasColumnType("bigint")
                        .HasColumnName("booking_status_id");

                    b.Property<Guid>("CalendarId")
                        .HasColumnType("uuid")
                        .HasColumnName("calendar_id");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("cancelled_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at");

                    b.Property<int>("NumberOfPassengers")
                        .HasColumnType("integer")
                        .HasColumnName("number_of_passengers");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp")
                        .HasColumnName("order_date");

                    b.Property<long>("TotalPrice")
                        .HasColumnType("bigint")
                        .HasColumnName("total_price");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("BookingStatusId");

                    b.HasIndex("CalendarId");

                    b.HasIndex("UserId");

                    b.ToTable("bookings");
                });

            modelBuilder.Entity("WaterTransportService.Model.Entities.BookingStatus", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("booking_statuses");
                });

            modelBuilder.Entity("WaterTransportService.Model.Entities.Calendar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ArrivedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("arrived_at");

                    b.Property<int>("CalendarStatusId")
                        .HasColumnType("integer")
                        .HasColumnName("status_id");

                    b.Property<DateTime>("DepartureAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("departure_at");

                    b.Property<Guid>("RouteId")
                        .HasColumnType("uuid")
                        .HasColumnName("route_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CalendarStatusId");

                    b.HasIndex("RouteId");

                    b.HasIndex("UserId");

                    b.ToTable("calendars");
                });

            modelBuilder.Entity("WaterTransportService.Model.Entities.CalendarStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("calendar_statuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Planned"
                        },
                        new
                        {
                            Id = 2,
                            Name = "OnTheWay"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Completed"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Cancelled"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Available"
                        },
                        new
                        {
                            Id = 6,
                            Name = "PartiallyAvailable"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Unavailable"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Blocked"
                        });
                });

            modelBuilder.Entity("WaterTransportService.Model.Entities.Password", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hash");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("salt");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<bool>("Version")
                        .HasColumnType("boolean")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("passwords");
                });

            modelBuilder.Entity("WaterTransportService.Model.Entities.Port", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("address");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<int>("PortTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("port_type_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("PortTypeId");

                    b.ToTable("ports");
                });

            modelBuilder.Entity("WaterTransportService.Model.Entities.PortImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("character varying(3000)")
                        .HasColumnName("image_path");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<Guid>("PortId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("uploaded_at");

                    b.HasKey("Id");

                    b.HasIndex("PortId");

                    b.ToTable("port_images");
                });

            modelBuilder.Entity("WaterTransportService.Model.Entities.PortType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.ToTable("port_types");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "Marine"
                        },
                        new
                        {
                            Id = 2,
                            Title = "Riverine"
                        },
                        new
                        {
                            Id = 3,
                            Title = "Estuaries"
                        },
                        new
                        {
                            Id = 4,
                            Title = "Riverbed"
                        },
                        new
                        {
                            Id = 5,
                            Title = "BucketPools"
                        },
                        new
                        {
                            Id = 6,
                            Title = "Closed"
                        },
                        new
                        {
                            Id = 7,
                            Title = "FormedByPiers"
                        });
                });

            modelBuilder.Entity("WaterTransportService.Model.Entities.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("comment");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<long>("Rating")
                        .HasColumnType("bigint")
                        .HasColumnName("rating");

                    b.Property<Guid?>("ShipId")
                        .HasColumnType("uuid")
                        .HasColumnName("ship_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("ShipId");

                    b.HasIndex("UserId");

                    b.ToTable("reviews");
                });

            modelBuilder.Entity("WaterTransportService.Model.Entities.Role", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("roles");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "User"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 3L,
                            Name = "Partner"
                        });
                });

            modelBuilder.Entity("WaterTransportService.Model.Entities.Route", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double>("Cost")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("cost");

                    b.Property<TimeSpan?>("DurationMinutes")
                        .HasColumnType("interval")
                        .HasColumnName("duration_minutes");

                    b.Property<Guid>("FromPortId")
                        .HasColumnType("uuid")
                        .HasColumnName("from_port_id");

                    b.Property<int>("RouteTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("route_type_id");

                    b.Property<Guid>("ShipId")
                        .HasColumnType("uuid")
                        .HasColumnName("ship_id");

                    b.Property<Guid?>("ToPortId")
                        .HasColumnType("uuid")
                        .HasColumnName("to_port_id");

                    b.HasKey("Id");

                    b.HasIndex("FromPortId");

                    b.HasIndex("RouteTypeId");

                    b.HasIndex("ShipId");

                    b.HasIndex("ToPortId");

                    b.ToTable("routes");
                });

            modelBuilder.Entity("WaterTransportService.Model.Entities.RouteType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("route_types");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Rental"
                        },
                        new
                        {
                            Id = 2,
                            Name = "FixedRoute"
                        });
                });

            modelBuilder.Entity("WaterTransportService.Model.Entities.Ship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<long?>("CostPerHour")
                        .HasColumnType("bigint")
                        .HasColumnName("cost_per_hour");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Engine")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("engine");

                    b.Property<int?>("Length")
                        .HasColumnType("integer")
                        .HasColumnName("length");

                    b.Property<int?>("MaxSpeed")
                        .HasColumnType("integer")
                        .HasColumnName("max_speed");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<Guid>("PortId")
                        .HasColumnType("uuid")
                        .HasColumnName("port_id");

                    b.Property<int?>("Power")
                        .HasColumnType("integer")
                        .HasColumnName("power");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("registration_number");

                    b.Property<int>("ShipTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("ship_type_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int?>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.Property<DateTime?>("YearOfManufacture")
                        .HasColumnType("timestamp")
                        .HasColumnName("year_of_manufacture");

                    b.HasKey("Id");

                    b.HasIndex("PortId");

                    b.HasIndex("ShipTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("ships");
                });

            modelBuilder.Entity("WaterTransportService.Model.Entities.ShipImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("character varying(3000)")
                        .HasColumnName("image_path");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<Guid>("ShipId")
                        .HasColumnType("uuid")
                        .HasColumnName("ship_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("uploaded_at");

                    b.HasKey("Id");

                    b.HasIndex("ShipId");

                    b.ToTable("ship_images");
                });

            modelBuilder.Entity("WaterTransportService.Model.Entities.ShipType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("ship_types");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Yacht"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Sailboat"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Motorboat"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Ferry"
                        },
                        new
                        {
                            Id = 5,
                            Name = "JetSki"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Barge"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Tugboat"
                        },
                        new
                        {
                            Id = 8,
                            Name = "RubberDinghy"
                        });
                });

            modelBuilder.Entity("WaterTransportService.Model.Entities.User", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at");

                    b.Property<int?>("FailedLoginAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("failed_login_attempts");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("last_login_at");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("timestamp")
                        .HasColumnName("locked_until");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("nickname");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Uuid");

                    b.ToTable("users");
                });

            modelBuilder.Entity("WaterTransportService.Model.Entities.UserImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("character varying(3000)")
                        .HasColumnName("image_path");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("uploaded_at");

                    b.Property<Guid?>("UserProfileUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileUserId");

                    b.ToTable("user_images");
                });

            modelBuilder.Entity("WaterTransportService.Model.Entities.UserProfile", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_uuid");

                    b.Property<string>("About")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("about");

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("date")
                        .HasColumnName("birthday");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_public");

                    b.Property<string>("LastName")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("last_name");

                    b.Property<string>("Location")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("location");

                    b.Property<string>("Patronymic")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("patronymic");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId");

                    b.ToTable("users_profiles");
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.HasOne("WaterTransportService.Model.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WaterTransportService.Model.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UsersUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WaterTransportService.Model.Entities.Booking", b =>
                {
                    b.HasOne("WaterTransportService.Model.Entities.BookingStatus", "BookingStatus")
                        .WithMany("Bookings")
                        .HasForeignKey("BookingStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WaterTransportService.Model.Entities.Calendar", "Calendar")
                        .WithMany()
                        .HasForeignKey("CalendarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WaterTransportService.Model.Entities.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BookingStatus");

                    b.Navigation("Calendar");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WaterTransportService.Model.Entities.Calendar", b =>
                {
                    b.HasOne("WaterTransportService.Model.Entities.CalendarStatus", "CalendarStatus")
                        .WithMany("Calendars")
                        .HasForeignKey("CalendarStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WaterTransportService.Model.Entities.Route", "Route")
                        .WithMany()
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WaterTransportService.Model.Entities.User", "User")
                        .WithMany("Calendars")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CalendarStatus");

                    b.Navigation("Route");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WaterTransportService.Model.Entities.Password", b =>
                {
                    b.HasOne("WaterTransportService.Model.Entities.User", "User")
                        .WithMany("Passwords")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WaterTransportService.Model.Entities.Port", b =>
                {
                    b.HasOne("WaterTransportService.Model.Entities.PortType", "PortType")
                        .WithMany("Ports")
                        .HasForeignKey("PortTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PortType");
                });

            modelBuilder.Entity("WaterTransportService.Model.Entities.PortImage", b =>
                {
                    b.HasOne("WaterTransportService.Model.Entities.Port", "Port")
                        .WithMany("PortImages")
                        .HasForeignKey("PortId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Port");
                });

            modelBuilder.Entity("WaterTransportService.Model.Entities.Review", b =>
                {
                    b.HasOne("WaterTransportService.Model.Entities.User", "Author")
                        .WithMany("Reviews")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WaterTransportService.Model.Entities.Ship", "Ship")
                        .WithMany("Reviews")
                        .HasForeignKey("ShipId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WaterTransportService.Model.Entities.User", "User")
                        .WithMany("ReceivedReviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Author");

                    b.Navigation("Ship");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WaterTransportService.Model.Entities.Route", b =>
                {
                    b.HasOne("WaterTransportService.Model.Entities.Port", "FromPort")
                        .WithMany()
                        .HasForeignKey("FromPortId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WaterTransportService.Model.Entities.RouteType", "RouteType")
                        .WithMany("Routes")
                        .HasForeignKey("RouteTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WaterTransportService.Model.Entities.Ship", "Ship")
                        .WithMany()
                        .HasForeignKey("ShipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WaterTransportService.Model.Entities.Port", "ToPort")
                        .WithMany()
                        .HasForeignKey("ToPortId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("FromPort");

                    b.Navigation("RouteType");

                    b.Navigation("Ship");

                    b.Navigation("ToPort");
                });

            modelBuilder.Entity("WaterTransportService.Model.Entities.Ship", b =>
                {
                    b.HasOne("WaterTransportService.Model.Entities.Port", "Port")
                        .WithMany("Ships")
                        .HasForeignKey("PortId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WaterTransportService.Model.Entities.ShipType", "ShipType")
                        .WithMany("Ships")
                        .HasForeignKey("ShipTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WaterTransportService.Model.Entities.User", "User")
                        .WithMany("Ships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Port");

                    b.Navigation("ShipType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WaterTransportService.Model.Entities.ShipImage", b =>
                {
                    b.HasOne("WaterTransportService.Model.Entities.Ship", "Ship")
                        .WithMany("ShipImages")
                        .HasForeignKey("ShipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ship");
                });

            modelBuilder.Entity("WaterTransportService.Model.Entities.UserImage", b =>
                {
                    b.HasOne("WaterTransportService.Model.Entities.UserProfile", null)
                        .WithMany("UserImages")
                        .HasForeignKey("UserProfileUserId");
                });

            modelBuilder.Entity("WaterTransportService.Model.Entities.UserProfile", b =>
                {
                    b.HasOne("WaterTransportService.Model.Entities.User", "User")
                        .WithOne("UserProfile")
                        .HasForeignKey("WaterTransportService.Model.Entities.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WaterTransportService.Model.Entities.BookingStatus", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("WaterTransportService.Model.Entities.CalendarStatus", b =>
                {
                    b.Navigation("Calendars");
                });

            modelBuilder.Entity("WaterTransportService.Model.Entities.Port", b =>
                {
                    b.Navigation("PortImages");

                    b.Navigation("Ships");
                });

            modelBuilder.Entity("WaterTransportService.Model.Entities.PortType", b =>
                {
                    b.Navigation("Ports");
                });

            modelBuilder.Entity("WaterTransportService.Model.Entities.RouteType", b =>
                {
                    b.Navigation("Routes");
                });

            modelBuilder.Entity("WaterTransportService.Model.Entities.Ship", b =>
                {
                    b.Navigation("Reviews");

                    b.Navigation("ShipImages");
                });

            modelBuilder.Entity("WaterTransportService.Model.Entities.ShipType", b =>
                {
                    b.Navigation("Ships");
                });

            modelBuilder.Entity("WaterTransportService.Model.Entities.User", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Calendars");

                    b.Navigation("Passwords");

                    b.Navigation("ReceivedReviews");

                    b.Navigation("Reviews");

                    b.Navigation("Ships");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("WaterTransportService.Model.Entities.UserProfile", b =>
                {
                    b.Navigation("UserImages");
                });
#pragma warning restore 612, 618
        }
    }
}
