// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WaterTransportService.Model.Context;

#nullable disable

namespace WaterTransportService.Model.Migrations
{
    [DbContext(typeof(WaterTransportDbContext))]
    [Migration("20251216160145_RewriteContext")]
    partial class RewriteContext
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WaterTransportService.Model.Entities.OldPassword", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("old_passwords");
                });

            modelBuilder.Entity("WaterTransportService.Model.Entities.Port", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("address");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<int>("PortTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("port_type_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("PortTypeId");

                    b.ToTable("ports");
                });

            modelBuilder.Entity("WaterTransportService.Model.Entities.PortImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("character varying(3000)")
                        .HasColumnName("image_path");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<Guid>("PortId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("uploaded_at");

                    b.HasKey("Id");

                    b.HasIndex("PortId");

                    b.ToTable("port_images");
                });

            modelBuilder.Entity("WaterTransportService.Model.Entities.PortType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.ToTable("port_types");
                });

            modelBuilder.Entity("WaterTransportService.Model.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("expires_at");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("token");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("refresh_tokens");
                });

            modelBuilder.Entity("WaterTransportService.Model.Entities.RentOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ArrivalPortId")
                        .HasColumnType("uuid")
                        .HasColumnName("arrival_port_id");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("cancelled_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DeparturePortId")
                        .HasColumnType("uuid")
                        .HasColumnName("departure_port_id");

                    b.Property<int>("NumberOfPassengers")
                        .HasColumnType("integer")
                        .HasColumnName("number_of_passengers");

                    b.Property<DateTime?>("OrderDate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("order_date");

                    b.Property<Guid?>("PartnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("partner_id");

                    b.Property<DateTime?>("RentalEndTime")
                        .HasColumnType("timestamptz")
                        .HasColumnName("rental_end_time");

                    b.Property<DateTime>("RentalStartTime")
                        .HasColumnType("timestamptz")
                        .HasColumnName("rental_start_time");

                    b.Property<Guid?>("ShipId")
                        .HasColumnType("uuid")
                        .HasColumnName("ship_id");

                    b.Property<int>("ShipTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("ship_type_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<long?>("TotalPrice")
                        .HasColumnType("bigint")
                        .HasColumnName("total_price");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ArrivalPortId");

                    b.HasIndex("DeparturePortId");

                    b.HasIndex("PartnerId");

                    b.HasIndex("ShipId");

                    b.HasIndex("ShipTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("rent_orders");
                });

            modelBuilder.Entity("WaterTransportService.Model.Entities.RentOrderOffer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<long>("OfferedPrice")
                        .HasColumnType("bigint")
                        .HasColumnName("offered_price");

                    b.Property<Guid>("PartnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("partner_id");

                    b.Property<Guid>("RentOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("rent_order_id");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("responded_at");

                    b.Property<Guid>("ShipId")
                        .HasColumnType("uuid")
                        .HasColumnName("ship_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("PartnerId");

                    b.HasIndex("RentOrderId");

                    b.HasIndex("ShipId");

                    b.ToTable("rent_order_offers");
                });

            modelBuilder.Entity("WaterTransportService.Model.Entities.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("comment");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid?>("PortId")
                        .HasColumnType("uuid")
                        .HasColumnName("port_id");

                    b.Property<float>("Rating")
                        .HasColumnType("real")
                        .HasColumnName("rating");

                    b.Property<Guid?>("RentOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("rent_order_id");

                    b.Property<Guid?>("ShipId")
                        .HasColumnType("uuid")
                        .HasColumnName("ship_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("PortId");

                    b.HasIndex("RentOrderId");

                    b.HasIndex("ShipId");

                    b.HasIndex("UserId");

                    b.ToTable("reviews");
                });

            modelBuilder.Entity("WaterTransportService.Model.Entities.Ship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<long?>("CostPerHour")
                        .HasColumnType("bigint")
                        .HasColumnName("cost_per_hour");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<int?>("Length")
                        .HasColumnType("integer")
                        .HasColumnName("length");

                    b.Property<int?>("MaxSpeed")
                        .HasColumnType("integer")
                        .HasColumnName("max_speed");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<Guid>("PortId")
                        .HasColumnType("uuid")
                        .HasColumnName("port_id");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("registration_number");

                    b.Property<int>("ShipTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("ship_type_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int?>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.Property<DateTime?>("YearOfManufacture")
                        .HasColumnType("timestamptz")
                        .HasColumnName("year_of_manufacture");

                    b.HasKey("Id");

                    b.HasIndex("PortId");

                    b.HasIndex("ShipTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("ships");
                });

            modelBuilder.Entity("WaterTransportService.Model.Entities.ShipImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("character varying(3000)")
                        .HasColumnName("image_path");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<Guid>("ShipId")
                        .HasColumnType("uuid")
                        .HasColumnName("ship_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("uploaded_at");

                    b.HasKey("Id");

                    b.HasIndex("ShipId");

                    b.ToTable("ship_images");
                });

            modelBuilder.Entity("WaterTransportService.Model.Entities.ShipRentalCalendar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ArrivalPortId")
                        .HasColumnType("uuid")
                        .HasColumnName("arrival_port_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("DeparturePortId")
                        .HasColumnType("uuid")
                        .HasColumnName("departure_port_id");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamptz")
                        .HasColumnName("end_time");

                    b.Property<Guid>("RentOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("rent_order_id");

                    b.Property<Guid>("ShipId")
                        .HasColumnType("uuid")
                        .HasColumnName("ship_id");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamptz")
                        .HasColumnName("start_time");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("RentOrderId")
                        .IsUnique();

                    b.HasIndex("ShipId");

                    b.ToTable("ship_rental_calendar");
                });

            modelBuilder.Entity("WaterTransportService.Model.Entities.ShipType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("ship_types");
                });

            modelBuilder.Entity("WaterTransportService.Model.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<int?>("FailedLoginAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("failed_login_attempts");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hash");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_login_at");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("timestamptz")
                        .HasColumnName("locked_until");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("WaterTransportService.Model.Entities.UserImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("character varying(3000)")
                        .HasColumnName("image_path");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("uploaded_at");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_profile_id");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId");

                    b.ToTable("user_images");
                });

            modelBuilder.Entity("WaterTransportService.Model.Entities.UserProfile", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_uuid");

                    b.Property<string>("About")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("about");

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("date")
                        .HasColumnName("birthday");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_public");

                    b.Property<string>("LastName")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("last_name");

                    b.Property<string>("Location")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("location");

                    b.Property<string>("Nickname")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("nickname");

                    b.Property<string>("Patronymic")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("patronymic");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId");

                    b.ToTable("users_profiles");
                });

            modelBuilder.Entity("WaterTransportService.Model.Entities.OldPassword", b =>
                {
                    b.HasOne("WaterTransportService.Model.Entities.User", null)
                        .WithMany("OldPasswords")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WaterTransportService.Model.Entities.Port", b =>
                {
                    b.HasOne("WaterTransportService.Model.Entities.PortType", "PortType")
                        .WithMany("Ports")
                        .HasForeignKey("PortTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PortType");
                });

            modelBuilder.Entity("WaterTransportService.Model.Entities.PortImage", b =>
                {
                    b.HasOne("WaterTransportService.Model.Entities.Port", "Port")
                        .WithMany("PortImages")
                        .HasForeignKey("PortId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Port");
                });

            modelBuilder.Entity("WaterTransportService.Model.Entities.RefreshToken", b =>
                {
                    b.HasOne("WaterTransportService.Model.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WaterTransportService.Model.Entities.RentOrder", b =>
                {
                    b.HasOne("WaterTransportService.Model.Entities.Port", "ArrivalPort")
                        .WithMany()
                        .HasForeignKey("ArrivalPortId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WaterTransportService.Model.Entities.Port", "DeparturePort")
                        .WithMany()
                        .HasForeignKey("DeparturePortId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WaterTransportService.Model.Entities.User", "Partner")
                        .WithMany()
                        .HasForeignKey("PartnerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WaterTransportService.Model.Entities.Ship", "Ship")
                        .WithMany()
                        .HasForeignKey("ShipId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WaterTransportService.Model.Entities.ShipType", "ShipType")
                        .WithMany()
                        .HasForeignKey("ShipTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WaterTransportService.Model.Entities.User", "User")
                        .WithMany("RentOrders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ArrivalPort");

                    b.Navigation("DeparturePort");

                    b.Navigation("Partner");

                    b.Navigation("Ship");

                    b.Navigation("ShipType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WaterTransportService.Model.Entities.RentOrderOffer", b =>
                {
                    b.HasOne("WaterTransportService.Model.Entities.User", "Partner")
                        .WithMany()
                        .HasForeignKey("PartnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WaterTransportService.Model.Entities.RentOrder", "RentOrder")
                        .WithMany("Offers")
                        .HasForeignKey("RentOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WaterTransportService.Model.Entities.Ship", "Ship")
                        .WithMany()
                        .HasForeignKey("ShipId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Partner");

                    b.Navigation("RentOrder");

                    b.Navigation("Ship");
                });

            modelBuilder.Entity("WaterTransportService.Model.Entities.Review", b =>
                {
                    b.HasOne("WaterTransportService.Model.Entities.User", "Author")
                        .WithMany("Reviews")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WaterTransportService.Model.Entities.Port", null)
                        .WithMany("Reviews")
                        .HasForeignKey("PortId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WaterTransportService.Model.Entities.RentOrder", "RentOrder")
                        .WithMany("Reviews")
                        .HasForeignKey("RentOrderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WaterTransportService.Model.Entities.Ship", null)
                        .WithMany("Reviews")
                        .HasForeignKey("ShipId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WaterTransportService.Model.Entities.User", null)
                        .WithMany("ReceivedReviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Author");

                    b.Navigation("RentOrder");
                });

            modelBuilder.Entity("WaterTransportService.Model.Entities.Ship", b =>
                {
                    b.HasOne("WaterTransportService.Model.Entities.Port", "Port")
                        .WithMany("Ships")
                        .HasForeignKey("PortId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WaterTransportService.Model.Entities.ShipType", "ShipType")
                        .WithMany("Ships")
                        .HasForeignKey("ShipTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WaterTransportService.Model.Entities.User", "User")
                        .WithMany("Ships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Port");

                    b.Navigation("ShipType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WaterTransportService.Model.Entities.ShipImage", b =>
                {
                    b.HasOne("WaterTransportService.Model.Entities.Ship", "Ship")
                        .WithMany("ShipImages")
                        .HasForeignKey("ShipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ship");
                });

            modelBuilder.Entity("WaterTransportService.Model.Entities.ShipRentalCalendar", b =>
                {
                    b.HasOne("WaterTransportService.Model.Entities.RentOrder", "RentOrder")
                        .WithOne("ShipRentalCalendarEntry")
                        .HasForeignKey("WaterTransportService.Model.Entities.ShipRentalCalendar", "RentOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WaterTransportService.Model.Entities.Ship", "Ship")
                        .WithMany("RentalCalendarEntries")
                        .HasForeignKey("ShipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RentOrder");

                    b.Navigation("Ship");
                });

            modelBuilder.Entity("WaterTransportService.Model.Entities.UserImage", b =>
                {
                    b.HasOne("WaterTransportService.Model.Entities.UserProfile", "UserProfile")
                        .WithMany("UserImages")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("WaterTransportService.Model.Entities.UserProfile", b =>
                {
                    b.HasOne("WaterTransportService.Model.Entities.User", null)
                        .WithOne("UserProfile")
                        .HasForeignKey("WaterTransportService.Model.Entities.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WaterTransportService.Model.Entities.Port", b =>
                {
                    b.Navigation("PortImages");

                    b.Navigation("Reviews");

                    b.Navigation("Ships");
                });

            modelBuilder.Entity("WaterTransportService.Model.Entities.PortType", b =>
                {
                    b.Navigation("Ports");
                });

            modelBuilder.Entity("WaterTransportService.Model.Entities.RentOrder", b =>
                {
                    b.Navigation("Offers");

                    b.Navigation("Reviews");

                    b.Navigation("ShipRentalCalendarEntry");
                });

            modelBuilder.Entity("WaterTransportService.Model.Entities.Ship", b =>
                {
                    b.Navigation("RentalCalendarEntries");

                    b.Navigation("Reviews");

                    b.Navigation("ShipImages");
                });

            modelBuilder.Entity("WaterTransportService.Model.Entities.ShipType", b =>
                {
                    b.Navigation("Ships");
                });

            modelBuilder.Entity("WaterTransportService.Model.Entities.User", b =>
                {
                    b.Navigation("OldPasswords");

                    b.Navigation("ReceivedReviews");

                    b.Navigation("RentOrders");

                    b.Navigation("Reviews");

                    b.Navigation("Ships");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("WaterTransportService.Model.Entities.UserProfile", b =>
                {
                    b.Navigation("UserImages");
                });
#pragma warning restore 612, 618
        }
    }
}
