#!/bin/bash
set -e

: "${APP_USER:?APP_USER is required}"
: "${APP_PASSWORD:?APP_PASSWORD is required}"

psql -v ON_ERROR_STOP=1 \
  --username "$POSTGRES_USER" \
  --dbname "$POSTGRES_DB" \
  -v APP_USER="$APP_USER" \
  -v APP_PASSWORD="$APP_PASSWORD" <<-EOSQL
  CREATE USER :"APP_USER" WITH PASSWORD :'APP_PASSWORD' NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT;

  GRANT CONNECT ON DATABASE "$POSTGRES_DB" TO :"APP_USER";
  GRANT USAGE ON SCHEMA public TO :"APP_USER";
  GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO :"APP_USER";
  GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO :"APP_USER";

  ALTER DEFAULT PRIVILEGES IN SCHEMA public
      GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO :"APP_USER";
  ALTER DEFAULT PRIVILEGES IN SCHEMA public
      GRANT USAGE, SELECT ON SEQUENCES TO :"APP_USER";
EOSQL
